name: GitHub Actions Demo
run-name: Automatisation de terraform
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: terraform init
      - run: terraform plan -input=false
